---

  - hosts: Routers
    become: yes

    tasks:
      - name: Enable Interfaces
        cisco.ios.ios_config:
          lines:
            - interface range gigabitethernet0/0-1
            - no shutdown
            - exit
            
      - name: Create Sub-Interfaces
        cisco.ios.ios_config:
          lines:
            - interface gigabitethernet0/0.3
            - description LAN-Data
            - encapsulation dot1q 3
            - ip address 10.'{{ site_id }}'.3.254 255.255.255.0
            - ip helper-address '{{ dhcp-primary }}'
            - ip helper-address '{{ dhcp-secondary }}'
            - ip helper-address '{{ radius-primary }}'
            - ip helper-address '{{ radius-secondary }}'
            - no ip redirects
            - interface gigabitethernet0/0.4
            - description Facilities
            - encapsulation dot1q 4
            - ip address 10.'{{ site_id }}'.4.254 255.255.255.0
            - ip helper-address '{{ dhcp-primary }}'
            - ip helper-address '{{ dhcp-secondary }}'
            - ip helper-address '{{ radius-primary }}'
            - ip helper-address '{{ radius-secondary }}'
            - no ip redirects
            - interface gigabitethernet0/0.5
            - description ECR/Printers
            - encapsulation dot1q 5
            - ip address 10.'{{ site_id }}'.5.254 255.255.255.0
            - ip helper-address '{{ dhcp-primary }}'
            - ip helper-address '{{ dhcp-secondary }}'
            - ip helper-address '{{ radius-primary }}'
            - ip helper-address '{{ radius-secondary }}'
            - no ip redirects
            - interface gigabitethernet0/0.13
            - description Video
            - encapsulation dot1q 13
            - ip address 10.'{{ site_id }}'.13.254 255.255.255.0
            - ip helper-address '{{ dhcp-primary }}'
            - ip helper-address '{{ dhcp-secondary }}'
            - ip helper-address '{{ radius-primary }}'
            - ip helper-address '{{ radius-secondary }}'
            - no ip redirects
            - interface gigabitethernet0/0.18
            - description Vendor
            - encapsulation dot1q 18
            - ip address 172.18.'{{ site_id }}'.254 255.255.255.0
            - ip helper-address '{{ dhcp-primary }}'
            - ip helper-address '{{ dhcp-secondary }}'
            - ip helper-address '{{ radius-primary }}'
            - ip helper-address '{{ radius-secondary }}'
            - no ip redirects
            - interface gigabitethernet0/0.50
            - description Voice
            - encapsulation dot1q 50
            - ip address 10.'{{ site_id }}'.50.254 255.255.255.0
            - ip helper-address '{{ dhcp-primary }}'
            - ip helper-address '{{ dhcp-secondary }}'
            - ip helper-address '{{ radius-primary }}'
            - ip helper-address '{{ radius-secondary }}'
            - no ip redirects
            - interface gigabitethernet0/0.252
            - description Wifi-Data
            - encapsulation dot1q 252
            - ip address 10.'{{ site_id }}'.252.254 255.255.255.0
            - ip helper-address '{{ dhcp-primary }}'
            - ip helper-address '{{ dhcp-secondary }}'
            - ip helper-address '{{ radius-primary }}'
            - ip helper-address '{{ radius-secondary }}'
            - no ip redirects
            - interface gigabitethernet0/0.254
            - description Wifi-MGMT
            - encapsulation dot1q 254
            - ip address 10.'{{ site_id }}'.254.254 255.255.255.0
            - ip helper-address '{{ dhcp-primary }}'
            - ip helper-address '{{ dhcp-secondary }}'
            - ip helper-address '{{ radius-primary }}'
            - ip helper-address '{{ radius-secondary }}'
            - no ip redirects
            - interface gigabitethernet0/0.255
            - description Management
            - encapsulation dot1q 255
            - ip address 10.'{{ site_id }}'.255.254 255.255.255.0
            - ip helper-address '{{ dhcp-primary }}'
            - ip helper-address '{{ dhcp-secondary }}'
            - ip helper-address '{{ radius-primary }}'
            - ip helper-address '{{ radius-secondary }}'
            - no ip redirects
            - interface gigabitethernet0/0.991
            - description ATMs
            - encapsulation dot1q 991
            - ip address 172.17.'{{ site_id }}'.254 255.255.255.0
            - ip helper-address '{{ dhcp-primary }}'
            - ip helper-address '{{ dhcp-secondary }}'
            - ip helper-address '{{ radius-primary }}'
            - ip helper-address '{{ radius-secondary }}'
            - no ip redirects
            - interface gigabitethernet0/0.4000
            - description Isolation
            - encapsulation dot1q 4000
            - ip address 172.31.'{{ site_id }}'.254 255.255.255.0
            - ip helper-address '{{ dhcp-primary }}'
            - ip helper-address '{{ dhcp-secondary }}'
            - ip helper-address '{{ radius-primary }}'
            - ip helper-address '{{ radius-secondary }}'
            - no ip redirects


      - name: Write Memory
        cisco.ios.ios_config:
          lines:
            - copy run start

